// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"AXY_TitleMenu","status":true,"description":"v1.00 Display Multiple Menu in Title Screen.","parameters":{"DisplayJumpToMap":"false","JumpToMapText":"JumpToMap","JumpToMapId":"1","JumpToMapSwitchId":"0","DisplayExit":"true","ExitText":"退出游戏","MaxCols":"1","WindowWidth":"300","X":"(Graphics.boxWidth - this.width) / 2-150","Y":"Graphics.boxHeight - this.height - 96-300","WindowSkin":"Window2","Align":"center","TextColor":"#FFFFFF"}},
{"name":"TitleCommandPosition","status":false,"description":"Changes the position of the title command window.","parameters":{"Offset X":"0","Offset Y":"0","Width":"240","Background":"0"}},
{"name":"EnemyBook","status":true,"description":"Displays detailed statuses of enemies.","parameters":{"Unknown Data":"??????"}},
{"name":"ItemBook","status":true,"description":"Displays detailed statuses of items.","parameters":{"Unknown Data":"??????","Price Text":"Price","Equip Text":"Equip","Type Text":"Type"}},
{"name":"WeaponSkill","status":true,"description":"Change skill id of attack for each weapon.","parameters":{}},
{"name":"SimpleMsgSideView","status":true,"description":"at sideview battle, only display item/skill names.","parameters":{"displayAttack":"1","position":"1"}}
];
